// <auto-generated />
using System;
using ApiMiniApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiMiniApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523152515_mig_5")]
    partial class mig_5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiMiniApp.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ApiMiniApp.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BannerImageUrl = "/uploads/banners/techsummit.jpg",
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2025, 9, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Крупнейшая технологическая конференция года с участием мировых спикеров.",
                            IsDeleted = false,
                            Location = "Baku Convention Center, Баку",
                            OrganizerId = 1,
                            Title = "Tech Summit 2025"
                        },
                        new
                        {
                            Id = 2,
                            BannerImageUrl = "/uploads/banners/artfall.jpg",
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2025, 10, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Выставка работ молодых художников Азербайджана.",
                            IsDeleted = false,
                            Location = "ArtSpace Gallery, ул. Низами 42, Баку",
                            OrganizerId = 2,
                            Title = "Современное искусство: Осень"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2025, 11, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ежегодный городской марафон по центру Баку.",
                            IsDeleted = false,
                            Location = "Площадь Азадлыг, Баку",
                            OrganizerId = 3,
                            Title = "Бакинский марафон 2025"
                        },
                        new
                        {
                            Id = 4,
                            BannerImageUrl = "/uploads/banners/jazz.jpg",
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2025, 8, 20, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Вечер живой джазовой музыки под открытым небом.",
                            IsDeleted = false,
                            Location = "Приморский бульвар, Баку",
                            OrganizerId = 4,
                            Title = "Jazz Under The Stars"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2025, 9, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Интенсивный трёхдневный курс по Python для начинающих и продолжающих.",
                            IsDeleted = false,
                            Location = "EduWorld Campus, пр. Матбуат 102",
                            OrganizerId = 5,
                            Title = "Python Bootcamp"
                        },
                        new
                        {
                            Id = 6,
                            BannerImageUrl = "/uploads/banners/pitch.jpg",
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2025, 10, 18, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Вечер презентаций стартапов перед венчурными инвесторами.",
                            IsDeleted = false,
                            Location = "Baku Tech Hub, ул. Рашида Бейбутова 10",
                            OrganizerId = 1,
                            Title = "Startup Pitch Night"
                        });
                });

            modelBuilder.Entity("ApiMiniApp.Models.Organizer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Organizers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            Email = "contact@techconf.az",
                            IsDeleted = false,
                            LogoUrl = "/uploads/logos/techconf.png",
                            Name = "TechConf Inc.",
                            Phone = "+994501234567"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            Email = "info@artspace.az",
                            IsDeleted = false,
                            LogoUrl = "/uploads/logos/artspace.png",
                            Name = "ArtSpace Baku",
                            Phone = "+994552345678"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hello@sportlife.az",
                            IsDeleted = false,
                            LogoUrl = "/uploads/logos/sportlife.png",
                            Name = "SportLife Agency",
                            Phone = "+994703456789"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            Email = "press@musicfest.az",
                            IsDeleted = false,
                            LogoUrl = "/uploads/logos/musicfest.png",
                            Name = "MusicFest Org"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            Email = "edu@eduworld.az",
                            IsDeleted = false,
                            Name = "EduWorld Azerbaijan",
                            Phone = "+994514567890"
                        });
                });

            modelBuilder.Entity("ApiMiniApp.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Tickets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 1,
                            IsDeleted = false,
                            Price = 299.99m,
                            QuantityAvailable = 50,
                            Type = "VIP"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 1,
                            IsDeleted = false,
                            Price = 99.99m,
                            QuantityAvailable = 300,
                            Type = "Regular"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 1,
                            IsDeleted = false,
                            Price = 49.99m,
                            QuantityAvailable = 100,
                            Type = "Student"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 2,
                            IsDeleted = false,
                            Price = 15.00m,
                            QuantityAvailable = 200,
                            Type = "Regular"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 2,
                            IsDeleted = false,
                            Price = 35.00m,
                            QuantityAvailable = 30,
                            Type = "VIP"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 3,
                            IsDeleted = false,
                            Price = 25.00m,
                            QuantityAvailable = 500,
                            Type = "Participant"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 3,
                            IsDeleted = false,
                            Price = 75.00m,
                            QuantityAvailable = 20,
                            Type = "VIP"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 4,
                            IsDeleted = false,
                            Price = 20.00m,
                            QuantityAvailable = 150,
                            Type = "Regular"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 4,
                            IsDeleted = false,
                            Price = 60.00m,
                            QuantityAvailable = 40,
                            Type = "VIP"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 4,
                            IsDeleted = false,
                            Price = 200.00m,
                            QuantityAvailable = 10,
                            Type = "Table"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 5,
                            IsDeleted = false,
                            Price = 120.00m,
                            QuantityAvailable = 80,
                            Type = "Regular"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 5,
                            IsDeleted = false,
                            Price = 199.99m,
                            QuantityAvailable = 15,
                            Type = "VIP"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 6,
                            IsDeleted = false,
                            Price = 0.00m,
                            QuantityAvailable = 100,
                            Type = "General"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 5, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 6,
                            IsDeleted = false,
                            Price = 50.00m,
                            QuantityAvailable = 25,
                            Type = "Investor"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ApiMiniApp.Models.Event", b =>
                {
                    b.HasOne("ApiMiniApp.Models.Organizer", "Organizer")
                        .WithMany("Events")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("ApiMiniApp.Models.Ticket", b =>
                {
                    b.HasOne("ApiMiniApp.Models.Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApiMiniApp.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApiMiniApp.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiMiniApp.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApiMiniApp.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiMiniApp.Models.Event", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ApiMiniApp.Models.Organizer", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
